Penn 9-10
friends-library/william-penn pull request #8
Opened 2020-06-17 19:58 UTC by maijapapaya

@jaredh159 @Henderjay

2020-06-17 20:05 UTC, maijapapaya commented on life/modernized/09-chapter-9.adoc
> +It was first published in the year 1694, as follows.
I removed the colon after "as follows" because the asterisks seem to break it up too much.

2020-06-18 18:28 UTC, Henderjay requested changes
Just one numbered group in chapter 10 modernized that needs the new syntax, as noted. The rest looks perfect.

2020-06-18 18:28 UTC, Henderjay commented on life/modernized/10-chapter-10.adoc
> +[.numbered]
This numbered group needs the new syntax... with the [.numbered-group] tag, and the ==== before and after. The other two numbered groups in this chapter are perfect. 👍🏻

2020-06-23 17:41 UTC, merged

2020-06-23 17:41 UTC, Henderjay commented
looks great, merged.